### ISSUE TITLE
/random无法访问

### ISSUE THREAD

**Issue by MomentQYC** [mzdluo123/rs_pixiv#1]
如题，`cargo build --release`自编译的程序，已知部署环境可以访问Pixiv，部署后发现random显示破图且状态码为404，且无任何错误输出
直接访问/random也是直接404，不管是反代还是直接访问IP都是这样
不管是直接运行还是systemd也是都这样

**Comment by mzdluo123** [comment]
哦 忘记说了，你需要设置`PIXIV_COOKIE`环境变量来让程序可以访问你的账户，从而从你的收藏夹里获得数据

格式为字符串，只需要复制http请求头里面的cookie就行了

**Comment by MomentQYC** [comment]
> 哦 忘记说了，你需要设置`PIXIV_COOKIE`环境变量来让程序可以访问你的账户，从而从你的收藏夹里获得数据
> 
> 格式为字符串，只需要复制http请求头里面的cookie就行了

将PIXIV_COOKIE和PIXIV_UID都写入环境变量后重启服务依然如此
![image](https://user-images.githubusercontent.com/62551256/210062460-0a0e2c78-9d80-447c-a508-3ed9cc0dabb9.png)

**Comment by mzdluo123** [comment]
可以设置RUST_LOG环境变量为debug来查看日志，日志可能有一些帮助 （虽然我好像也没打印什么日志

**Comment by MomentQYC** [comment]
直接运行持续会出现报错
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidLength', simple_pixiv/src/main.rs:43:16
stack backtrace:
   0:     0x559b9ed46c50 - <unknown>
   1:     0x559b9ec059be - <unknown>
   2:     0x559b9ed22ec4 - <unknown>
   3:     0x559b9ed47f7f - <unknown>
   4:     0x559b9ed47b7f - <unknown>
   5:     0x559b9ed48c18 - <unknown>
   6:     0x559b9ed486e2 - <unknown>
   7:     0x559b9ed4864c - <unknown>
   8:     0x559b9ed48621 - <unknown>
   9:     0x559b9ea376c2 - <unknown>
  10:     0x559b9ea37962 - <unknown>
  11:     0x559b9eb1646c - <unknown>
  12:     0x559b9eaf4346 - <unknown>
  13:     0x559b9eb0cf01 - <unknown>
  14:     0x559b9eaa5933 - <unknown>
  15:     0x559b9eaa5e1e - <unknown>
  16:     0x559b9eb17927 - <unknown>
  17:     0x7fd3037a1083 - __libc_start_main
  18:     0x559b9ea4541e - <unknown>
  19:                0x0 - <unknown>
```

出现报错后就退出了，systemd运行则可以持续
运行环境没有安装Rust，编译的环境是rustc1.66，rustup1.25.1，cargo1.66

**Comment by mzdluo123** [comment]
尝试使用debug模式编译获得更多信息，此外之前的版本的确有这个问题，你可以从master分支拉最新的代码试试看

**Comment by mzdluo123** [comment]
我去检查一下 ，可能是我之前修改的代码出现了问题

**Comment by mzdluo123** [comment]
啊 真不好意思 是我记错了，cookie需要使用base64编码

这个项目部署之后我就几乎没管它，而且是我初学rust的学习项目。。。

写得不好请见谅

**Comment by MomentQYC** [comment]
> cookie需要使用base64编码

已解决，感谢
